language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - travis_retry composer self-update

script:
  - phpunit --verbose tests/MockTest

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0
  fast_finish: true
